# Use an official Nginx image as a base image
FROM nginx:latest

# Remove the default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy your custom Nginx configuration
COPY vhost-ai-ticulate-production.nginx.config /etc/nginx/conf.d/default.conf

# Copy the built artifacts from the frontend service
COPY --from=kyleheat/ai-ticulate:client /app/dist /var/www/ai-ticulate-client

# Expose ports
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
