####################
# Production Image #
####################
FROM node:lts-alpine

# Create working directory
WORKDIR /app

# Install dependencies
COPY package*.json .
RUN npm ci

RUN echo "ls -la"
# Copy files
COPY . .

# Environment variables
COPY .env.example .env

# Use the node user instead of root
USER node

# Expose port
EXPOSE 80

# Start the app
CMD ["node", "app.js"]

